Repository Douglas-CRVG/Driven-BuzzQuizz, pull requests merged in 2021-11, with the labels that each got.

#2 Layout tela 1
  css/reset.css
  css/styles.css
  img/pencil.png
  index.html
  script/index.js
Labels: enhancement

#3 Hotfix map
  index.html
  script/index.js
Labels: bug

#4 add validations for creation of quizzes
  css/styles.css
  script/index.js
Labels: enhancement

#5 add obj 'createQuiz'
  script/index.js
Labels: enhancement

#6 Questions create quiz
  css/styles.css
  script/index.js
Labels: bug, enhancement

#7 Showing a quiz
  css/styles.css
  script/index.js
Labels: bug, enhancement

#8 Quiz levels
  css/styles.css
  script/index.js
Labels: enhancement

#9 fix bug in form validations and adding func for list my quizzes
  css/styles.css
  script/index.js
Labels: bug, enhancement

#11 fix bug in myQuiz and adding loading screen in createQuiz
  css/styles.css
  img/loading.png
  script/index.js
Labels: bug, enhancement

#10 fix bugs in renderMyQuiz
  script/index.js
Labels: bug

#12 adding function for deleting a quiz
  css/styles.css
  script/index.js
Labels: enhancement

#13 bug render MyQuizzes
  script/index.js
Labels: bug
